### ISSUE TITLE
feat: Implement logic for tables in backend

### ISSUE THREAD

**Issue by luka-jaredic3110** [F1sssss/Lavirint#9]
Needed entities:
- Room (eg. "Terrace", "Inside - Floor 1", "Inside - Basement")
- Table (serves as a visual representation of an Order Group)

Relationships:
- A restaurant can have many rooms.
- A room can have many tables.
- A room can belong to only one restaurant.
- A table can belong to only one room.
- A table can have only one group.
- A group can belong to many tables ????

Properties of a Room:
- `width`: Decimal number (how many `px` is room wide)
- `height`: Decimal number (how many `px` is room high)
- `name`: String (what is the name of the room)
- `tables`: Array of objects (which tables are in here)
- `ALL THE ABOVE PROPERTIES I WILL SEND TO YOU ON CREATE`
- `id` - Autogenerated by you.

Properties of Table:
- `left`: Decimal (The positional `left` of the table)
- `top`: Decimal (The positional `top` of the table)
- `angle`: Decimal (Tells me about the rotation of table)
- `scaleX`: Decimal (Tells me about the stretch of the table)
- `scaleY`: Decimal (Tells me about the stretch of the table)
- `isCircle`: Boolean (is the table circle or rect)
- `group_id`: Integer ( id of the group represented by the table )
- `ALL THE ABOVE PROPERTIES I WILL SEND TO YOU ON CREATE`
- `id`: autogenerated by you
- `group_name`:  String (name of the group represented by the table - I will not send this on create, but I need it on GET)
- `group_total`: Decimal (unsummerized total of this group - I will not send it, but need it on GET)

Example of entities that I want to use:

```JS
const my_rooms = [
    {
        "id": 3000,
        "width": 1324,
        "height": 624.1738100207282,
        "name": "Novi prostor",
        "tables": [
            {
                "id": 83,
                "left": 49,
                "top": 87,
                "angle": 0,
                "scaleX": 1,
                "scaleY": 1,
                "isCircle": false,
                "group_id": 1,
                "group_name": "Šank 1",
                "group_total": 107.01
            },
            {
                "id": 84,
                "left": 305,
                "top": 84,
                "angle": 0,
                "scaleX": 1,
                "scaleY": 1,
                "isCircle": true,
                "group_id": 2,
                "group_name": "Sto 13",
                "group_total": 0
            }...
        ]
]
```

**Comment by F1sssss** [comment]
This issue can be closed as the logic has been implemented per commits 1bdf190 and 6dbcaa5

Tables object is a bit different, as in it doesn't return ```group_total``` bu returns the next params

```
 {
     'ukupna_cijena_osnovna' : Decimal / null
      'ukupna_cijena_rabatisana' : Decimal / null
      'ukupna_cijena_puna' : Decimal / nullz
      'ukupna_cijena_prodajna' : Decimal / null
      'porez_iznos' : Decimal / null
      'rabat_iznos_osnovni' : Decimal / null
      'rabat_iznos_prodajni' : Decimal / null
      'tax_exemption_amount' : Decimal / null
}
```
